# ~/.tmuxinator/local.yml

name: local
root: ~/

project_name: local
project_root: ~/
windows:
  - local:
      layout: 67d7,208x64,0,0{105x64,0,0,83,102x64,106,0[102x36,106,0,84,102x27,106,37,85]}
      panes:
        - cd ~/.Files/; ls -lah
        - cd ~/; ls -lah
        - sudo softwareupdate --install --all -v; sudo brew update; sudo brew upgrade; sudo /opt/chef/embedded/bin/gem update
